# Key settings (must edit)
project_title: KD5081
project_repo: johncoxon/KD5081
admins:
- johncoxon
- matthewtownson
- r-pallister
instructors:
- johncoxon
- matthewtownson
- r-pallister
students:
- johncoxon
- matthewtownson
- r-pallister
web_address: https://johncoxon.github.io/KD5081

# User options (may edit)
questions: true
votes_required: 3
gh-pages: true