admins:
- johncoxon
- matthewtownson
- r-pallister
gh-pages: true
instructors:
- johncoxon
- matthewtownson
- r-pallister
project_repo: johncoxon/KD5081
project_title: KD5081
questions: true
students:
- johncoxon
- matthewtownson
- r-pallister
- Yigitaliozcan58
- r-pallister
- Nasher47
- w23013189
- w23055700
votes_required: 3
web_address: https://johncoxon.github.io/KD5081
